# Site settings
title: Ulrica Skarin
email: ls222xp@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  Web programming student in quest of a deeper understanding
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: acirlu33
github_username:  ulricaskarin

# Build settings
markdown: kramdown

