# Site settings
title: A dev students quest
author: Ulrica Skarin
email: ls222xp@student.lnu.se
description:  A dev students quest
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ulricaskarin.github.io" # the base hostname & protocol for your site

#pagination
paginate: 4

# Social Media
twitter_username: acirlu33
github_username:  ulricaskarin

# Comments
comments:
    provider: disqus
    disqus:
        short_name: lillulli
    intensedebate:
        account: lillulli

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed

# Build settings
markdown: kramdown
timezone: Europe/Stockholm

