# Site settings
title: A dev students quest
logourl: localhost:4000/assets/images/us_logo.png
author: Ulrica Skarin
email: ls222xp@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  A dev students quest to find a deeper understanding by Ulrica Skarin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site

#pagination
paginate: 4

# Social Media
twitter_username: acirlu33
github_username:  ulricaskarin

# Comments
comments:
    provider: disqus
    disqus:
        short_name: lillulli
    livefyre:
        site_id:3
    intensedebate:
        account: lillulli

# Build settings
markdown: kramdown
timezone: Europe/Stockholm

